version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safebill_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - safebill_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: safebill_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - safebill_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: safebill_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: safebill
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: safebill
      MYSQL_USER: safebill
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - safebill_network

volumes:
  mysql_data:
    driver: local

networks:
  safebill_network:
    driver: bridge