services:
  safebillpro-nginx:
    image: rash07/nginx
    container_name: safebillpro-nginx
    working_dir: /var/www/html
    environment:
      VIRTUAL_HOST: safebill.dev, *.safebill.dev
    volumes:
      - ./:/var/www/html
      - /var/www/safebill.dev/proxy/fpms/app:/etc/nginx/sites-available
    restart: always
    networks:
      - proxynet

  safebillpro-fpm:
    image: rash07/php-fpm:7.4
    container_name: safebillpro-fpm
    working_dir: /var/www/html
    volumes:
      - ./ssh:/root/.ssh
      - ./ssh:/var/www/.ssh
      - ./:/var/www/html
    restart: always
    networks:
      - proxynet

  safebillpro-mariadb:
    image: mariadb:10.5.6
    container_name: safebillpro-mariadb
    environment:
      MYSQL_USER: safebillpro
      MYSQL_PASSWORD: JSeuITqrtkQDTqhqFUvf
      MYSQL_DATABASE: safebillpro
      MYSQL_ROOT_PASSWORD: yrRqwIkY20qZmryaSmOP
      MYSQL_PORT_HOST: 3306
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - proxynet

  safebillpro-redis:
    image: redis:alpine
    container_name: safebillpro-redis
    volumes:
      - redisdata:/data
    restart: always
    networks:
      - proxynet

  safebillpro-scheduling:
    image: rash07/scheduling
    container_name: safebillpro-scheduling
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - proxynet

  safebillpro-supervisor:
    image: rash07/php7.4-supervisor
    container_name: safebillpro-supervisor
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    restart: always
    networks:
      - proxynet

networks:
  proxynet:
    external: true

volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local
